export interface BrandProfile {
  id: string;
  primaryName: string;
  aliases: string[];
  legitimateDomains: string[];
  category: "BANKING" | "FINTECH" | "TECH" | "ECOMMERCE" | "GOVERNMENT" | "LOGISTICS" | "TELECOM";
  country?: string;
  authoritativeSource: string;
}

export const BRAND_REGISTRY: BrandProfile[] = [
  // --- Indian Banking & Fintech ---
  {
    id: "hdfc-bank",
    primaryName: "HDFC Bank",
    aliases: ["hdfc", "hdfc bank", "hdfc netbanking", "hdfc bank ltd"],
    legitimateDomains: ["hdfcbank.com", "hdfc.com", "hdfc.bank.in"],
    category: "BANKING",
    country: "IN",
    authoritativeSource: "RBI Scheduled Commercial Banks Registry / Official Domain Registrar",
  },
  {
    id: "state-bank-of-india",
    primaryName: "State Bank of India",
    aliases: ["sbi", "state bank of india", "onlinesbi", "yono sbi"],
    legitimateDomains: ["sbi.co.in", "onlinesbi.sbi", "onlinesbi.com", "sbi.bank.in"],
    category: "BANKING",
    country: "IN",
    authoritativeSource: "RBI Scheduled Commercial Banks Registry",
  },
  {
    id: "icici-bank",
    primaryName: "ICICI Bank",
    aliases: ["icici", "icici bank", "icici netbanking"],
    legitimateDomains: ["icicibank.com", "icicibank.co.in", "icici.bank.in"],
    category: "BANKING",
    country: "IN",
    authoritativeSource: "RBI Scheduled Commercial Banks Registry",
  },
  {
    id: "axis-bank",
    primaryName: "Axis Bank",
    aliases: ["axis", "axis bank"],
    legitimateDomains: ["axisbank.com", "axis.bank.in"],
    category: "BANKING",
    country: "IN",
    authoritativeSource: "RBI Scheduled Commercial Banks Registry",
  },
  {
    id: "kotak-bank",
    primaryName: "Kotak Mahindra Bank",
    aliases: ["kotak", "kotak mahindra bank", "kotak 811"],
    legitimateDomains: ["kotak.com", "kotak.bank.in"],
    category: "BANKING",
    country: "IN",
    authoritativeSource: "RBI Scheduled Commercial Banks Registry",
  },
  {
    id: "paytm",
    primaryName: "Paytm",
    aliases: ["paytm", "paytm payments bank"],
    legitimateDomains: ["paytm.com", "paytmbank.com"],
    category: "FINTECH",
    country: "IN",
    authoritativeSource: "NPCI / RBI Payment Aggregator Registry",
  },
  {
    id: "phonepe",
    primaryName: "PhonePe",
    aliases: ["phonepe", "phone pe"],
    legitimateDomains: ["phonepe.com"],
    category: "FINTECH",
    country: "IN",
    authoritativeSource: "NPCI Verified Entities",
  },
  {
    id: "india-post",
    primaryName: "India Post",
    aliases: ["india post", "dak seva", "speed post"],
    legitimateDomains: ["indiapost.gov.in", "ippbonline.com"],
    category: "LOGISTICS",
    country: "IN",
    authoritativeSource: "National Portal of India (.gov.in)",
  },

  // --- Global Tech & E-Commerce ---
  {
    id: "paypal",
    primaryName: "PayPal",
    aliases: ["paypal", "pay pal"],
    legitimateDomains: ["paypal.com", "paypal.me"],
    category: "FINTECH",
    authoritativeSource: "PayPal Inc. Corporate Entity & Global Trademark Registry",
  },
  {
    id: "google",
    primaryName: "Google",
    aliases: ["google", "gmail", "google drive", "google pay", "google play"],
    legitimateDomains: ["google.com", "gmail.com", "google.co.in", "accounts.google.com", "pay.google.com"],
    category: "TECH",
    authoritativeSource: "Alphabet Inc. Registered Domains",
  },
  {
    id: "microsoft",
    primaryName: "Microsoft",
    aliases: ["microsoft", "bing", "office 365", "outlook", "onedrive", "microsoft account", "windows"],
    legitimateDomains: ["microsoft.com", "live.com", "outlook.com", "office.com", "microsoftonline.com", "bing.com"],
    category: "TECH",
    authoritativeSource: "Microsoft Corporation Verified Registry",
  },
  {
    id: "apple",
    primaryName: "Apple",
    aliases: ["apple", "icloud", "apple id", "app store"],
    legitimateDomains: ["apple.com", "icloud.com"],
    category: "TECH",
    authoritativeSource: "Apple Inc. Registry",
  },
  {
    id: "amazon",
    primaryName: "Amazon",
    aliases: ["amazon", "amazon prime", "amazon pay"],
    legitimateDomains: ["amazon.com", "amazon.in", "amazon.co.uk", "amazon.de"],
    category: "ECOMMERCE",
    authoritativeSource: "Amazon.com Inc. Registry",
  },
  {
    id: "netflix",
    primaryName: "Netflix",
    aliases: ["netflix", "netflix support"],
    legitimateDomains: ["netflix.com"],
    category: "TECH",
    authoritativeSource: "Netflix Inc. Official Domain",
  },
  {
    id: "meta",
    primaryName: "Meta",
    aliases: ["meta", "facebook", "instagram", "whatsapp"],
    legitimateDomains: ["facebook.com", "instagram.com", "whatsapp.com", "meta.com", "fb.com"],
    category: "TECH",
    authoritativeSource: "Meta Platforms Inc.",
  },

  // --- US / Global Banking ---
  {
    id: "chase",
    primaryName: "Chase Bank",
    aliases: ["chase", "jpmorgan chase", "chase bank"],
    legitimateDomains: ["chase.com", "jpmorgan.com"],
    category: "BANKING",
    country: "US",
    authoritativeSource: "FDIC Insured Financial Institutions",
  },
  {
    id: "wells-fargo",
    primaryName: "Wells Fargo",
    aliases: ["wells fargo", "wellsfargo"],
    legitimateDomains: ["wellsfargo.com"],
    category: "BANKING",
    country: "US",
    authoritativeSource: "FDIC Insured Financial Institutions",
  },
  {
    id: "bank-of-america",
    primaryName: "Bank of America",
    aliases: ["bank of america", "bofa"],
    legitimateDomains: ["bankofamerica.com", "bofa.com"],
    category: "BANKING",
    country: "US",
    authoritativeSource: "FDIC Insured Financial Institutions",
  },

  // --- Government & Public Institutions ---
  {
    id: "income-tax-india",
    primaryName: "Income Tax Department of India",
    aliases: ["income tax", "incometax", "e-filing", "itr", "income tax department"],
    legitimateDomains: ["incometax.gov.in", "incometaxindia.gov.in"],
    category: "GOVERNMENT",
    country: "IN",
    authoritativeSource: "Government of India (.gov.in registry)",
  },
  {
    id: "uidai-aadhaar",
    primaryName: "UIDAI Aadhaar",
    aliases: ["uidai", "aadhaar", "eaadhaar", "myaadhaar"],
    legitimateDomains: ["uidai.gov.in", "myaadhaar.uidai.gov.in"],
    category: "GOVERNMENT",
    country: "IN",
    authoritativeSource: "Government of India (.gov.in registry)",
  },
  {
    id: "usps",
    primaryName: "United States Postal Service",
    aliases: ["usps", "us postal service", "usps tracking"],
    legitimateDomains: ["usps.com"],
    category: "LOGISTICS",
    country: "US",
    authoritativeSource: "United States Postal Service Authority",
  },

  // --- Modern AI, Developer Platforms & Cloud ---
  {
    id: "openai",
    primaryName: "OpenAI",
    aliases: ["openai", "chatgpt", "gpt-4", "gpt-5", "dall-e", "sora", "openai api"],
    legitimateDomains: ["openai.com", "chatgpt.com", "oaistatic.com", "oaiusercontent.com"],
    category: "TECH",
    country: "US",
    authoritativeSource: "OpenAI Corporate Registry & Official Web Presence",
  },
  {
    id: "anthropic",
    primaryName: "Anthropic",
    aliases: ["anthropic", "claude", "claude ai", "anthropic claude", "claude sonnet", "claude opus"],
    legitimateDomains: ["anthropic.com", "claude.ai"],
    category: "TECH",
    country: "US",
    authoritativeSource: "Anthropic PBC Corporate Registry & Official Web Presence",
  },
  {
    id: "perplexity",
    primaryName: "Perplexity AI",
    aliases: ["perplexity", "perplexity ai", "perplexity pro"],
    legitimateDomains: ["perplexity.ai"],
    category: "TECH",
    country: "US",
    authoritativeSource: "Perplexity AI Official Registrar",
  },
  {
    id: "mistral",
    primaryName: "Mistral AI",
    aliases: ["mistral", "mistral ai", "le chat"],
    legitimateDomains: ["mistral.ai"],
    category: "TECH",
    country: "FR",
    authoritativeSource: "Mistral AI Official Registrar",
  },
  {
    id: "deepmind",
    primaryName: "Google DeepMind",
    aliases: ["deepmind", "google deepmind"],
    legitimateDomains: ["deepmind.google", "deepmind.com", "gemini.google.com"],
    category: "TECH",
    country: "GB",
    authoritativeSource: "Google Alphabet Official Domains",
  },
  {
    id: "cohere",
    primaryName: "Cohere",
    aliases: ["cohere", "cohere ai"],
    legitimateDomains: ["cohere.com"],
    category: "TECH",
    country: "CA",
    authoritativeSource: "Cohere Official Registrar",
  },
  {
    id: "supabase",
    primaryName: "Supabase",
    aliases: ["supabase"],
    legitimateDomains: ["supabase.com", "supabase.co"],
    category: "TECH",
    country: "US",
    authoritativeSource: "Supabase Official Web Presence",
  },
  {
    id: "vercel",
    primaryName: "Vercel",
    aliases: ["vercel", "nextjs", "next.js"],
    legitimateDomains: ["vercel.com", "nextjs.org", "vercel.app"],
    category: "TECH",
    country: "US",
    authoritativeSource: "Vercel Inc. Official Web Presence",
  },
  {
    id: "stripe",
    primaryName: "Stripe",
    aliases: ["stripe", "stripe payments"],
    legitimateDomains: ["stripe.com"],
    category: "FINTECH",
    country: "US",
    authoritativeSource: "Stripe Inc. Official Web Presence",
  },
  {
    id: "cloudflare",
    primaryName: "Cloudflare",
    aliases: ["cloudflare", "cloudflare 1.1.1.1"],
    legitimateDomains: ["cloudflare.com"],
    category: "TECH",
    country: "US",
    authoritativeSource: "Cloudflare Inc. Official Web Presence",
  },
  {
    id: "github",
    primaryName: "GitHub",
    aliases: ["github", "github copilot"],
    legitimateDomains: ["github.com", "github.io", "githubusercontent.com"],
    category: "TECH",
    country: "US",
    authoritativeSource: "Microsoft / GitHub Official Web Presence",
  },
];
