import {
  InvestigationResult,
  InvestigationGraphNode,
  InvestigationGraphEdge,
  NodeEpistemicType,
  NodeVerificationStatus,
  GraphNodeType,
} from "../types";

export interface BuiltGraph {
  nodes: InvestigationGraphNode[];
  edges: InvestigationGraphEdge[];
}

/**
 * Builds a Directed Acyclic Graph (DAG) for the GraphMind Investigation Studio from an InvestigationResult.
 * 
 * EPISTEMIC PURITY PRINCIPLE:
 * - OBSERVED_FACT: Directly extracted telemetry (DOM elements, URLs, HTTP responses, forms).
 * - EXTERNALLY_VERIFIED: Confirmed against authoritative public records (Brand registry, ICANN TLD, VirusTotal).
 * - AI_INFERENCE: Synthesized behavioral hypothesis or MITRE ATT&CK chain generated by Gemini.
 * - USER_INQUIRY: Questions, challenges, and hypotheses initiated by the human investigator.
 * 
 * NEVER fabricates evidence or connections.
 */
export function buildInvestigationGraph(result: InvestigationResult): BuiltGraph {
  const nodes: InvestigationGraphNode[] = [];
  const edges: InvestigationGraphEdge[] = [];

  const now = result.createdAt || new Date().toISOString();
  const rootId = `node_root_${result.id}`;

  // 1. ROOT NODE: Investigation Target
  nodes.push({
    id: rootId,
    parentId: null,
    type: "ROOT_TARGET",
    epistemicType: "OBSERVED_FACT",
    verificationStatus: "OBSERVED",
    title: "Investigation Target",
    label: result.target,
    summary: `Target ${result.inputType} submitted for investigation. Overall Risk Score: ${result.riskAssessment?.score}/100 (${result.riskAssessment?.classification}).`,
    source: "User Submission & Initial Ingestion",
    confidence: "HIGH",
    timestamp: now,
    supportingEvidence: [result.target],
    technicalDetails: {
      inputType: result.inputType,
      id: result.id,
      score: result.riskAssessment?.score,
      classification: result.riskAssessment?.classification,
    },
    suggestedActions: [
      "Examine observed domain infrastructure",
      "Inspect claimed brand authorization",
      "Review captured form credentials",
    ],
    x: 60,
    y: 280,
    width: 320,
    height: 190,
  });

  // Layer tracking coordinates
  const LAYER_X_INFRA = 460;
  const LAYER_X_ANALYSIS = 880;
  const LAYER_X_VERDICT = 1300;
  const LAYER_X_ATTACK = 1720;

  let infraY = 100;
  let analysisY = 80;
  let verdictY = 120;
  let attackY = 100;

  // 2. DOMAIN INFRASTRUCTURE NODES (Observed Fact)
  const domainNodeId = `node_domain_${result.id}`;
  const hostname = result.urlAnalysis?.hostname || "Observed Host";
  const registeredDomain = result.urlAnalysis?.registeredDomain || hostname;

  nodes.push({
    id: domainNodeId,
    parentId: rootId,
    type: "DOMAIN",
    epistemicType: "OBSERVED_FACT",
    verificationStatus: "OBSERVED",
    title: "Domain Infrastructure",
    label: hostname,
    summary: `Observed hostname: '${hostname}'. Registered domain: '${registeredDomain}'. Protocol: ${result.urlAnalysis?.protocol || "https:"}.`,
    source: "URL Parser & Public DNS Resolution",
    confidence: "HIGH",
    timestamp: now,
    supportingEvidence: [
      `Hostname: ${hostname}`,
      `Registered Domain: ${registeredDomain}`,
      `Top-Level Domain (TLD): ${result.urlAnalysis?.tld || "unknown"}`,
    ],
    technicalDetails: {
      hostname,
      registeredDomain,
      subdomain: result.urlAnalysis?.subdomain,
      tld: result.urlAnalysis?.tld,
      ip: result.urlAnalysis?.ip,
      isPunycode: result.urlAnalysis?.isPunycode,
    },
    suggestedActions: [
      "Check domain age & WHOIS records",
      "Verify if TLD is restricted or corporate-owned",
    ],
    x: LAYER_X_INFRA,
    y: infraY,
    width: 330,
    height: 190,
  });

  edges.push({
    id: `edge_${rootId}_${domainNodeId}`,
    fromId: rootId,
    toId: domainNodeId,
    relation: "resolves_to",
    strength: "STRONG",
  });
  infraY += 230;

  // 2b. REDIRECT CHAIN (if any observed)
  if (result.pageAnalysis?.redirectChain && result.pageAnalysis.redirectChain.length > 0) {
    const redirectNodeId = `node_redirect_${result.id}`;
    const hops = result.pageAnalysis.redirectChain;
    nodes.push({
      id: redirectNodeId,
      parentId: domainNodeId,
      type: "REDIRECT",
      epistemicType: "OBSERVED_FACT",
      verificationStatus: "OBSERVED",
      title: "Network Redirect Chain",
      label: `${hops.length} Redirect Hop${hops.length > 1 ? "s" : ""}`,
      summary: `Traffic traverses ${hops.length} intermediary redirect(s) before reaching final destination '${result.pageAnalysis.finalUrl}'.`,
      source: "HTTP Network Trace",
      confidence: "HIGH",
      timestamp: now,
      supportingEvidence: hops,
      technicalDetails: {
        hops,
        finalUrl: result.pageAnalysis.finalUrl,
        httpStatus: result.pageAnalysis.httpStatus,
      },
      suggestedActions: [
        "Analyze intermediary redirect hops for cloaking or evasive routing",
      ],
      x: LAYER_X_INFRA,
      y: infraY,
      width: 330,
      height: 180,
    });

    edges.push({
      id: `edge_${domainNodeId}_${redirectNodeId}`,
      fromId: domainNodeId,
      toId: redirectNodeId,
      relation: "redirects_through",
      strength: "STRONG",
    });
    infraY += 210;
  }

  // 3. CLAIMED BRAND NODE (Observed / Claimed)
  let brandNodeId: string | null = null;
  if (result.brandVerification?.claimedBrand) {
    brandNodeId = `node_brand_${result.id}`;
    const claimedName = result.brandVerification.claimedBrand;
    nodes.push({
      id: brandNodeId,
      parentId: domainNodeId,
      type: "CLAIMED_BRAND",
      epistemicType: "OBSERVED_FACT",
      verificationStatus: "OBSERVED",
      title: "Claimed Identity",
      label: claimedName,
      summary: `Page cues, headers, and meta titles claim representation of '${claimedName}'.`,
      source: "Page DOM Brand Extractor & Meta Analysis",
      confidence: "HIGH",
      timestamp: now,
      supportingEvidence: [
        `Claimed Brand Cue: ${claimedName}`,
        `Title: ${result.pageAnalysis?.title || "N/A"}`,
      ],
      technicalDetails: {
        claimedBrand: claimedName,
        expectedDomains: result.brandVerification.expectedDomains,
      },
      suggestedActions: [
        "Compare claimed brand against authoritative brand registry",
        "Verify if current domain matches authentic registry entries",
      ],
      x: LAYER_X_ANALYSIS,
      y: analysisY,
      width: 330,
      height: 180,
    });

    edges.push({
      id: `edge_${domainNodeId}_${brandNodeId}`,
      fromId: domainNodeId,
      toId: brandNodeId,
      relation: "claims_identity",
      strength: "STRONG",
    });
    analysisY += 220;
  }

  // 4. SUSPICIOUS FORMS & CREDENTIAL INPUTS (Observed Fact)
  if (result.pageAnalysis && (result.pageAnalysis.hasCredentialForm || result.pageAnalysis.hasOtpForm || result.pageAnalysis.forms?.length)) {
    const formNodeId = `node_forms_${result.id}`;
    const hasCred = result.pageAnalysis.hasCredentialForm;
    const hasOtp = result.pageAnalysis.hasOtpForm;
    const hasCrossDomain = result.pageAnalysis.hasCrossDomainForm;

    const summaryParts: string[] = [];
    if (hasCred) summaryParts.push("Password Harvesting Form");
    if (hasOtp) summaryParts.push("2FA / OTP Token Field");
    if (hasCrossDomain) summaryParts.push("Cross-Domain Exfiltration Action");

    nodes.push({
      id: formNodeId,
      parentId: domainNodeId,
      type: "SUSPICIOUS_FORM",
      epistemicType: "OBSERVED_FACT",
      verificationStatus: "OBSERVED",
      title: "Captured Form Fields",
      label: summaryParts.join(" + ") || "Form Elements",
      summary: `Identified interactive input fields on the webpage. ${hasCred ? "Includes password entry. " : ""}${hasOtp ? "Includes OTP capture. " : ""}${hasCrossDomain ? "Submits data to an external domain. " : ""}`,
      source: "DOM Security Sensor & Cheerio Element Parser",
      confidence: "HIGH",
      timestamp: now,
      supportingEvidence: result.pageAnalysis.forms?.map(f => `Action: ${f.action || "(self)"} | Method: ${f.method || "POST"} | Inputs: ${f.inputs.map(i => i.name || i.type).join(", ")}`) || ["Input fields present in DOM"],
      technicalDetails: {
        hasCredentialForm: hasCred,
        hasOtpForm: hasOtp,
        hasPaymentForm: result.pageAnalysis.hasPaymentForm,
        hasCrossDomainForm: hasCrossDomain,
        formCount: result.pageAnalysis.forms?.length || 0,
      },
      suggestedActions: [
        "Audit external form submission endpoint",
        "Check whether form is authorized by the claimed institution",
      ],
      x: LAYER_X_ANALYSIS,
      y: analysisY,
      width: 340,
      height: 200,
    });

    edges.push({
      id: `edge_${domainNodeId}_${formNodeId}`,
      fromId: domainNodeId,
      toId: formNodeId,
      relation: "hosts_form",
      strength: hasCred || hasCrossDomain ? "SUSPICIOUS" : "STRONG",
    });
    analysisY += 230;
  }

  // 5. SOCIAL ENGINEERING & URGENCY INDICATORS (Observed Fact)
  if (result.pageAnalysis?.urgencyIndicators && result.pageAnalysis.urgencyIndicators.length > 0) {
    const urgencyNodeId = `node_urgency_${result.id}`;
    nodes.push({
      id: urgencyNodeId,
      parentId: domainNodeId,
      type: "EVIDENCE_SIGNAL",
      epistemicType: "OBSERVED_FACT",
      verificationStatus: "OBSERVED",
      title: "Artificial Urgency Cues",
      label: "Coercive Urgency Text",
      summary: `Detected high-pressure psychological language designed to compel immediate victim action: ${result.pageAnalysis.urgencyIndicators.slice(0, 2).map(u => `"${u}"`).join(", ")}.`,
      source: "NLP Behavioral Heuristics Engine",
      confidence: "HIGH",
      timestamp: now,
      supportingEvidence: result.pageAnalysis.urgencyIndicators,
      technicalDetails: {
        urgencyIndicators: result.pageAnalysis.urgencyIndicators,
        socialEngineeringKeywords: result.pageAnalysis.socialEngineeringKeywords,
      },
      suggestedActions: [
        "Compare urgency claims with official account verification procedures",
      ],
      x: LAYER_X_ANALYSIS,
      y: analysisY,
      width: 330,
      height: 180,
    });

    edges.push({
      id: `edge_${domainNodeId}_${urgencyNodeId}`,
      fromId: domainNodeId,
      toId: urgencyNodeId,
      relation: "exhibits_urgency",
      strength: "SUSPICIOUS",
    });
    analysisY += 210;
  }

  // 6. BRAND VERIFICATION VERDICT (Externally Verified)
  if (result.brandVerification) {
    const verdictNodeId = `node_verdict_${result.id}`;
    const status = result.brandVerification.status;
    const isMatch = status === "MATCH";
    const isMismatch = status === "MISMATCH";

    nodes.push({
      id: verdictNodeId,
      parentId: brandNodeId || domainNodeId,
      type: "VERIFICATION_VERDICT",
      epistemicType: "EXTERNALLY_VERIFIED",
      verificationStatus: isMatch ? "VERIFIED" : isMismatch ? "CONFLICTING" : "UNVERIFIED",
      title: "Authoritative Verification",
      label: `Identity ${status}`,
      summary: result.brandVerification.reason,
      source: result.brandVerification.verificationSource || "TrustLens Authoritative Registry",
      confidence: result.brandVerification.confidence === "high" ? "HIGH" : "MEDIUM",
      timestamp: now,
      supportingEvidence: [
        `Claimed: ${result.brandVerification.claimedBrand}`,
        `Observed Host: ${result.brandVerification.observedDomain}`,
        `Authorized Official Domains: [${result.brandVerification.expectedDomains.join(", ")}]`,
      ],
      technicalDetails: {
        status,
        confidence: result.brandVerification.confidence,
        expectedDomains: result.brandVerification.expectedDomains,
        verificationSource: result.brandVerification.verificationSource,
      },
      suggestedActions: isMismatch
        ? [
            "Flag as high-confidence brand impersonation",
            "Examine whether combosquatting tricks are used in registered domain",
          ]
        : [
            "Confirm SSL certificate and legitimate infrastructure alignment",
          ],
      x: LAYER_X_VERDICT,
      y: verdictY,
      width: 340,
      height: 210,
    });

    edges.push({
      id: `edge_${brandNodeId || domainNodeId}_${verdictNodeId}`,
      fromId: brandNodeId || domainNodeId,
      toId: verdictNodeId,
      relation: isMatch ? "verified_as" : "conflicts_with",
      strength: isMismatch ? "SUSPICIOUS" : "STRONG",
    });
    verdictY += 240;
  }

  // 7. THREAT INTELLIGENCE (Externally Verified)
  if (result.threatIntel && result.threatIntel.length > 0) {
    const tiNodeId = `node_threatintel_${result.id}`;
    const flagged = result.threatIntel.filter(t => t.isMalicious);
    nodes.push({
      id: tiNodeId,
      parentId: domainNodeId,
      type: "EVIDENCE_SIGNAL",
      epistemicType: "EXTERNALLY_VERIFIED",
      verificationStatus: flagged.length > 0 ? "VERIFIED" : "UNVERIFIED",
      title: "Threat Intelligence Feeds",
      label: flagged.length > 0 ? `${flagged.length} Malicious Feeds` : "Clean Intel Feeds",
      summary: flagged.length > 0
        ? `Flagged by security feeds: ${flagged.map(f => `${f.source} (${f.details})`).join("; ")}.`
        : `Queried external threat feeds. No active threat listings reported at time of scan.`,
      source: "VirusTotal & Google SafeBrowsing API",
      confidence: "HIGH",
      timestamp: now,
      supportingEvidence: result.threatIntel.map(t => `${t.source}: ${t.isMalicious ? "MALICIOUS" : "CLEAN"} (${t.details})`),
      technicalDetails: {
        threatIntel: result.threatIntel,
      },
      suggestedActions: [
        "Correlate local heuristic signals with third-party threat vendor results",
      ],
      x: LAYER_X_VERDICT,
      y: verdictY,
      width: 330,
      height: 180,
    });

    edges.push({
      id: `edge_${domainNodeId}_${tiNodeId}`,
      fromId: domainNodeId,
      toId: tiNodeId,
      relation: "cross_referenced_with",
      strength: flagged.length > 0 ? "SUSPICIOUS" : "STRONG",
    });
    verdictY += 210;
  }

  // 8. AI ATTACK CHAIN INFERENCES (AI Inference)
  if (result.aiAssessment?.attackChain && result.aiAssessment.attackChain.length > 0) {
    let lastAttackNodeId: string = rootId;

    result.aiAssessment.attackChain.forEach((step, idx) => {
      const stepNodeId = `node_attack_${result.id}_step_${step.step}`;
      nodes.push({
        id: stepNodeId,
        parentId: lastAttackNodeId,
        type: "ATTACK_CHAIN_STAGE",
        epistemicType: "AI_INFERENCE",
        verificationStatus: "INFERRED",
        title: `MITRE Stage ${step.step}: ${step.stage}`,
        label: step.stage,
        summary: step.description,
        source: "Gemini Forensic Attack Chain Synthesis Engine",
        confidence: result.aiAssessment.modelConfidence >= 80 ? "HIGH" : "MEDIUM",
        timestamp: now,
        supportingEvidence: step.evidenceIds?.map(eId => {
          const item = result.evidence.find(ev => ev.id === eId);
          return item ? `[${item.category}] ${item.title}` : `Evidence #${eId}`;
        }) || [],
        technicalDetails: {
          step: step.step,
          stage: step.stage,
          modelConfidence: result.aiAssessment.modelConfidence,
          evidenceIds: step.evidenceIds,
        },
        suggestedActions: [
          "Evaluate potential containment actions for this attack phase",
          "Challenge or question this reasoning step",
        ],
        x: LAYER_X_ATTACK,
        y: attackY,
        width: 340,
        height: 190,
      });

      edges.push({
        id: `edge_${lastAttackNodeId}_${stepNodeId}`,
        fromId: lastAttackNodeId,
        toId: stepNodeId,
        relation: "infers_stage",
        strength: "INFERRED",
      });

      lastAttackNodeId = stepNodeId;
      attackY += 220;
    });
  }

  return { nodes, edges };
}
